baseURL = 'https://mukhitdinov.xyz/'
languageCode = 'en-us'
title = 'Isroil Mukhitdinov'
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
paginate  = 18
disableHugoGeneratorInject = true


[params]
ava = "/img/isroilmukhitdinov.png"
js = "/js/main.js"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"